# Generated by Django 5.1.2 on 2024-12-02 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Team',
        ),
    ]
