# Generated by Django 5.1.2 on 2024-12-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcareapp', '0002_rename_owner_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner',
            new_name='team',
        ),
    ]
