# Generated by Django 5.1.2 on 2024-12-02 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcareapp', '0003_rename_owner_dog_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogcareapp.item'),
        ),
    ]
